### ISSUE TITLE
Multiple timelines not working?

### ISSUE THREAD

**Issue by PauloFerreira** [timeglider/jquery_widget#37]
Hello, i download your last snapshot of the program and inserted a json file with 2 timelines, one that you provided, but it isn't working... Don't know what is the problem, may you help me?

**Comment by timeglider** [comment]
Could you email the JSON file to me, and I'll
give it a look: michael@timeglider.com

On Sat, Feb 18, 2012 at 3:54 PM, PauloFerreira <
reply@reply.github.com

**Comment by PauloFerreira** [comment]
Hello again, we communicated through e-mails and it has been concluded that the problem was that i have been loading the files locally, however i am using a server (apache) from where i load the files, so that can't be the problem...

**Comment by timeglider** [comment]
Hi Paulo

I realized this morning, while waking up, that I may not
have pushed my latest files to Github (even though I
moved them to the timeglider.com/jquery website...)
I just pushed a bunch of changes: See what happens
if you re-download the TG_ files.

Apologies...

Michael

On Tue, Feb 21, 2012 at 9:45 AM, PauloFerreira <
reply@reply.github.com

**Comment by PauloFerreira** [comment]
First of all, thanks for the time spent on this.

I downloaded the files and used the same JSON file that i sent you but it still doesn't work. I tried with all the browsers.

If it is the last update it doesn't make sense working on the timeglider.com/jquery website but not in my computer... I don't know why it doesn't work...
